---
- name: "Install postgres server"
  apt:
    pkg:
      - postgresql
      - postgresql-contrib
    state: present
    force: yes
    update_cache: yes

- name: "Create only office user"
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  no_log: true

- name: "Create the database specified in vars"
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    template: 'template0'
    state: present

- name: "Ensure user has access to the new database"
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present
  no_log: true

- name: "Ensure user does not have unnecessary permissions"
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  no_log: true
